### ISSUE TITLE
Refactor checkFifoFlags and checkFifoOverflow

### ISSUE THREAD

**Issue by stresingbuero** [Entwicklungsburo-Stresing/EBST_CAM#107]
- eliminate magic numbers
- use ReadBitS0_32 or ReadBitS0_8 after closing https://github.com/Entwicklungsburo-Stresing/EBST_CAM/issues/106
- rename to CheckFifoValid

**Comment by sinneD-O** [comment]
54548330ed3c75c25df93a143c86c00fd38ab19d
