### ISSUE TITLE
xy value tooltip doesn't work for first and last pixel

### ISSUE THREAD

**Issue by gldhnchn** [Entwicklungsburo-Stresing/EBST_CAM#122]
![image](https://github.com/Entwicklungsburo-Stresing/EBST_CAM/assets/24368572/21873db2-8936-4716-a7c6-e2f05af7b403)
![image](https://github.com/Entwicklungsburo-Stresing/EBST_CAM/assets/24368572/1f8b4f38-1b0e-4c9b-88ad-6e94a8dd9835)
![image](https://github.com/Entwicklungsburo-Stresing/EBST_CAM/assets/24368572/0c01364d-d25c-4e7f-8c21-2da5927d8586)

**Comment by sinneD-O** [comment]
16b9a07dcbdd5552befc6208b088263b1af30e94
