### ISSUE TITLE
Add camera control output options feature

### ISSUE THREAD

**Issue by gldhnchn** [Entwicklungsburo-Stresing/EBST_CAM#125]

**Comment by sinneD-O** [comment]
17555c2c2fdbb2bcca7054019dade37fe3cfc616

**Comment by gldhnchn** [comment]
This commit c8ec601df33992a9e29a7cc96717e8e4245685cd fixes the compile error. Revert it when the combo box is added.

**Comment by sinneD-O** [comment]
f61aeaffa8e6389f2f7dfeed662b293047de8607
