### ISSUE TITLE
downstream port containment

### ISSUE THREAD

**Issue by ghost** [Entwicklungsburo-Stresing/EBST_CAM#61]
Bernhard Lang 15.11.2021:
> Das Problem mit dem bei mir beobachteten Treiber-Absturz findet sich in den Logfiles als DPC oder "downstream port containment", was soweit ich es eruieren konnte bedeutet, dass ein PCI Gerät versucht auf Adressen zuzugreifen (DMA), die nicht vorgängig beim System dafür konfiguriert worden sind. Also z.B. wenn über die Grenze eines reservierten DMA Speichers hinaus geschrieben wird. Passiert das, dann klemmt ein spezieller System-Treiber die betroffene PCI Hardware vom Bus ab und ruft die entsprechende remove Funktion auf (-> remove_lscpcie). Danach wird der PCI Bus neu enumeriert und das Gerät wieder neu initialisiert (-> probe_lscpcie). Dabei lief ich bisher in eine Schlaufe. Sobald der Treiber neu initialisiert wird, tritt wieder derselbe Fehler auf, das Gerät wird wieder vom Bus getrennt und danach neu initialisiert usw.
> 
> 1) Wenn man den Debian-Kernel neu übersetzt und dabei die per Default gesetzte Option "PCI Express Downstream Port Containment support" entfernt, laufen auch lsc-gui und lsc-cli ohne Treiberabstürze (aber keine ausgiebigen Tests meinerseits bisher). Das dürfte der Grund dafür sein, warum es bei Ihnen geht und bei mir nicht: im Kernel von Ubuntu ist diese Option standardmässig nicht aktiviert. Warum ein solcher "PCI Schreibfehler" keine Unstabilitäten im System verursacht, kann ich nicht sagen. Das zu verstehen wäre aber wohl schon ein Anliegen, bevor der Treiber "in die Produktion" geht.
> 
> 2) Um die oben erläuterte Absturz-Schleife zu unterbinden, hatte ich ein Rücksetzen des DMA mittels Schreiben von 1 und danach 0 in das niedrigste Bit des ersten DMA Registers beim Laden des Treibers eingefügt, gleich nachdem die PCI Register gemappt worden sind (pcie.c ungefähr Zeile 90, äquivalent eines Aufrufs von reset_dma() in dma.c). Überraschender Weise tritt der DPC Fehler dann bereits bei dieser Operation auf, ohne dass zuvor DMA angestossen worden war. Sieht auf den ersten Blick also wie ein Sideeffect beim "Anfassen" dieses Bits aus.
> 
> 3) Ob 2) direkt mit der Ursache der Abstürze während des Messens zu tun hat, ist damit noch nicht geklärt. Es wird lediglich derselbe Fehler-Typ im Logfile vermerkt. Ich habe jedoch beobachtet, dass bei meinem eigenen Programm die Abstürze nicht auftreten, wenn man den Rechner danach in Ruhe lässt. Schon Mausoperationen, hin und her schieben, oder ein Menü zum Skalieren der Plots aufklappen usw kann es auslösen. Es könnte also sein, dass "um die Interrupt Routine herum" noch ein Problem der Synchronisation zwischen Zählern in der Hardware und im Treiber besteht, wenn vor dem Bearbeiten eines Interrupts noch ein weiterer auftritt. Warum ein solches Problem zu mehr als zu einem Datenverlust innerhalb der Treiber-Puffer führen sollte, ist mir zwar noch nicht klar. Aber der Teufel steckt ja bekanntlich im Detail.

Bernhard Lang 28.07.2021:

> In Board.c wird in Zeile 153 SetDmaStartMode aufgerufen. Darin wird im IRQREG bit 30 gesetzt, das das DMA aktiviert. Exakt nach Setzen dieses Bits tritt der DPC containment error auf. SetDmaRegister wird in Board.c aber erst danach, in Zeile 157 aufgerufen. Kann es sein, dass die Karte bereits nach SetDmaStartMode los läuft, weil noch ein Bit für externes Triggern "überlebt" hat oder so etwas? Für mich sieht es so aus, als ob die Karte hier bereits los läuft, obwohl die DMA Register zumindest teilweise noch nicht initialisiert sind. Und dann ginge das DMA natürlich "in die Wüste", was den DPC containment error nach sich ziehen würde.

**Comment by gldhnchn** [comment]
closed as stale and not reproducable
